name: 3rd-eye Deploy
 
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      
      - name: Setup .npmrc
        run: |
          npm set @dwavelett:registry "https://npm.pkg.github.com"
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download packages
        run: npm install --production --always-auth

      - name: Build
        run: npm run build-only

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist